# Generated by Django 2.1.7 on 2019-02-21 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('payload', models.TextField(verbose_name='Payload')),
                ('meta', models.TextField(verbose_name='Meta')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('source', models.CharField(choices=[('GITHUB', 'GitHub'), ('GITLAB', 'GitLab'), ('BITBUCKET', 'Bitbucket')], max_length=50, verbose_name='Source')),
                ('url_hash', models.CharField(max_length=256, verbose_name='URL Hash')),
                ('secret', models.CharField(max_length=256, verbose_name='Secret')),
                ('last_trigger', models.DateTimeField(blank=True, null=True, verbose_name='Last Trigger')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Hook',
                'verbose_name_plural': 'Hooks',
                'db_table': 'hook',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished At')),
                ('successful', models.NullBooleanField(verbose_name='Successful')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Package Name')),
                ('description', models.TextField(verbose_name='Package Description')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'db_table': 'package',
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Repository Name')),
                ('url', models.CharField(max_length=250, verbose_name='Repository URL')),
                ('branch', models.CharField(max_length=200, verbose_name='Branch')),
                ('image', models.CharField(max_length=200, verbose_name='Docker Image')),
                ('directory', models.CharField(max_length=500, verbose_name='Directory')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'verbose_name': 'Repository',
                'verbose_name_plural': 'Repositories',
                'db_table': 'repository',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='hook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm.Hook', verbose_name='Hook'),
        ),
    ]
