# Generated by Django 2.1.7 on 2019-03-06 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0003_auto_20181106_1101'),
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_results.TaskResult', to_field='task_id'),
        ),
    ]
