# Generated by Django 2.1.7 on 2019-03-06 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_job_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='successful',
        ),
        migrations.AddField(
            model_name='job',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farm.Event'),
            preserve_default=False,
        ),
    ]
